services:
  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'status' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
  
  # notification-service:
  #   build:
  #     context: ./notification-service
  #     target: prod
  #   image: notification-service:prod
  #   container_name: notification-service
  #   ports:
  #     - '8080:8080'
  #   env_file:
  #     - ./notification-service/.env
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - default
  #   develop:
  #     watch:
  #       - path: ./notification-service
  #         action: sync
  #         target: /app
  #         ignore: node_modules

  #       - path: ./notification-service/package.json
  #         action: rebuild
