
POST http://localhost:3000/notifications
Content-Type: application/json

{
    "channel": "email",
    "payload": {
        "channel": "email",
        "to": "john@mail.com",
        "subject": "Notification",
        "body": "Hello, this is a test notification"
    }
}

###
GET http://localhost:3001/queues

###
GET http://localhost:3001/queues/dlq

###
GET http://localhost:3001/queues/stream
